/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import dao.EstoqueDAO;
import estoque.Estoque;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class TelaEstoque extends javax.swing.JFrame {
    DefaultTableModel dtm_tabela;
    ArrayList<Estoque> listaEstoque;

    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
        dtm_tabela = new DefaultTableModel(null, new String[]{"Codigo","Produto","Valor","Quantidade"});
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }
    
    private void atualizaTabela() throws SQLException, ClassNotFoundException
    {
        JTB_dados.setModel(dtm_tabela);
        dtm_tabela.setNumRows(0);
        listaEstoque = EstoqueDAO.buscarTodosProdutos();
        for (Estoque e : listaEstoque) 
        {
            dtm_tabela.addRow(new Object[]{e.getCodigo(), e.getProduto(), e.getValor(), e.getQtdeProduto()});
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_dados = new javax.swing.JTable();
        JLB_infoBuscar = new javax.swing.JLabel();
        JLB_codigo = new javax.swing.JLabel();
        JTF_codigo = new javax.swing.JTextField();
        JBT_buscar = new javax.swing.JButton();
        JLB_infoSaldo = new javax.swing.JLabel();
        JLB_saldo = new javax.swing.JLabel();
        JBT_saldo = new javax.swing.JButton();
        JBT_retornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTB_dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTB_dados);

        JLB_infoBuscar.setText("Buscar por codigo");

        JLB_codigo.setText("Codigo:");

        JBT_buscar.setText("Buscar");
        JBT_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_buscarActionPerformed(evt);
            }
        });

        JLB_infoSaldo.setText("Saldo em estoque:");

        JBT_saldo.setText("Exibir");
        JBT_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_saldoActionPerformed(evt);
            }
        });

        JBT_retornar.setText("Retornar");
        JBT_retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_retornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLB_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBT_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBT_retornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(JLB_infoSaldo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLB_codigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTF_codigo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(JLB_infoBuscar))
                            .addComponent(JBT_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLB_infoBuscar)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLB_codigo)
                            .addComponent(JTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBT_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(JLB_infoSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLB_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBT_saldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBT_retornar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBT_retornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_retornarActionPerformed
        TelaCadastro tela = new TelaCadastro();
        tela.setTitle("Controle Estoque - Cadastro");
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_JBT_retornarActionPerformed

    private void JBT_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_buscarActionPerformed
        String codigo = JTF_codigo.getText();
        ArrayList<Estoque> listaEstoque;
        listaEstoque = EstoqueDAO.buscarCodigo(codigo);
        JTB_dados.setModel(dtm_tabela);
        dtm_tabela.setNumRows(0);
        for (Estoque e : listaEstoque) 
        {
            dtm_tabela.addRow(new Object[]{e.getCodigo(), e.getProduto(), e.getValor(), e.getQtdeProduto()});
	}
    }//GEN-LAST:event_JBT_buscarActionPerformed

    private void JBT_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_saldoActionPerformed
        float saldo = 0;
        try {
            saldo = EstoqueDAO.saldo();
        } catch (SQLException ex) {
            Logger.getLogger(TelaEstoque.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaEstoque.class.getName()).log(Level.SEVERE, null, ex);
        }
        JLB_saldo.setText("O saldo em estoque é de: R$" + saldo);
    }//GEN-LAST:event_JBT_saldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBT_buscar;
    private javax.swing.JButton JBT_retornar;
    private javax.swing.JButton JBT_saldo;
    private javax.swing.JLabel JLB_codigo;
    private javax.swing.JLabel JLB_infoBuscar;
    private javax.swing.JLabel JLB_infoSaldo;
    private javax.swing.JLabel JLB_saldo;
    private javax.swing.JTable JTB_dados;
    private javax.swing.JTextField JTF_codigo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
