/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import dao.EstoqueDAO;
import estoque.Estoque;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class TelaVender extends javax.swing.JFrame {

    ArrayList<Estoque> listaEstoque;

    /**
     * Creates new form TelaVender
     */
    public TelaVender() {
        initComponents();
    }

    private void limparTela() {
        JTF_codigo.setText("");
        JTF_qtdeProduto.setText("");
        JTF_dinheiro.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLB_infoVendas = new javax.swing.JLabel();
        JLB_codigo = new javax.swing.JLabel();
        JTF_codigo = new javax.swing.JTextField();
        JLB_qtdeProduto = new javax.swing.JLabel();
        JTF_qtdeProduto = new javax.swing.JTextField();
        JBT_vender = new javax.swing.JButton();
        JLB_valor = new javax.swing.JLabel();
        JLB_dinheiro = new javax.swing.JLabel();
        JTF_dinheiro = new javax.swing.JTextField();
        JLB_troco = new javax.swing.JLabel();
        JBT_inicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLB_infoVendas.setText("Informe os dados da venda");

        JLB_codigo.setText("Codigo:");

        JLB_qtdeProduto.setText("Quantidade:");

        JBT_vender.setText("Vender");
        JBT_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_venderActionPerformed(evt);
            }
        });

        JLB_dinheiro.setText("Dinheiro:");

        JBT_inicio.setText("Retornar");
        JBT_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_inicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLB_infoVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBT_vender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLB_qtdeProduto)
                            .addComponent(JLB_codigo)
                            .addComponent(JLB_dinheiro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTF_dinheiro)
                            .addComponent(JTF_codigo)
                            .addComponent(JTF_qtdeProduto)))
                    .addComponent(JLB_valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLB_troco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBT_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLB_infoVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLB_codigo)
                    .addComponent(JTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLB_qtdeProduto)
                    .addComponent(JTF_qtdeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLB_dinheiro)
                    .addComponent(JTF_dinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(JBT_vender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLB_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLB_troco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBT_inicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBT_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_venderActionPerformed
        String codigo;
        float dinheiro;
        int qtdeProduto;
        codigo = JTF_codigo.getText();
        dinheiro = Float.parseFloat(JTF_dinheiro.getText());
        qtdeProduto = Integer.parseInt(JTF_qtdeProduto.getText());
        int resultado = 0;
        try {
            listaEstoque = EstoqueDAO.buscarTodosProdutos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
        }
        float valor = 0;
        for (int i = 0; i < listaEstoque.size(); i++) {
            if (listaEstoque.get(i).getCodigo().equals(codigo)) {
                valor = listaEstoque.get(i).getValor() * qtdeProduto;
            }
        }
        if (valor == 0) {
            JOptionPane.showMessageDialog(null, "Não é possivel realizar a venda, codigo não existe!");
            return;
        }
        if (dinheiro < valor) {
            JOptionPane.showMessageDialog(null, "Não é possivel realizar a venda, pagamento não suficiente!");
            return;
        } else {
            try {
                resultado = EstoqueDAO.vender(codigo, qtdeProduto);
            } catch (SQLException ex) {
                Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (resultado == 0) {
                JOptionPane.showMessageDialog(null, "Não foi possivel efetuar a venda, quantidade de produto indisponível!");
                return;
            } else {
                float troco = 0;
                troco = dinheiro - valor;
                JLB_valor.setText("Valor total: R$ " + Float.toString(valor));
                JLB_troco.setText("Troco: R$ " + Float.toString(troco));
                JOptionPane.showMessageDialog(null, "Venda realizada com sucesso!");
                limparTela();
            }
        }
    }//GEN-LAST:event_JBT_venderActionPerformed

    private void JBT_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_inicioActionPerformed
        TelaCadastro tela = new TelaCadastro();
        tela.setTitle("Controle Estoque - Cadastro");
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_JBT_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBT_inicio;
    private javax.swing.JButton JBT_vender;
    private javax.swing.JLabel JLB_codigo;
    private javax.swing.JLabel JLB_dinheiro;
    private javax.swing.JLabel JLB_infoVendas;
    private javax.swing.JLabel JLB_qtdeProduto;
    private javax.swing.JLabel JLB_troco;
    private javax.swing.JLabel JLB_valor;
    private javax.swing.JTextField JTF_codigo;
    private javax.swing.JTextField JTF_dinheiro;
    private javax.swing.JTextField JTF_qtdeProduto;
    // End of variables declaration//GEN-END:variables
}
