/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import dao.EstoqueDAO;
import estoque.Estoque;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class TelaCadastro extends javax.swing.JFrame {

    ArrayList<Estoque> listaEstoque;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    private void limparTela() {
        JTF_codigo.setText("");
        JTF_produto.setText("");
        JTF_valor.setText("");
        JTF_qtdeProduto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLB_codigo = new javax.swing.JLabel();
        JTF_codigo = new javax.swing.JTextField();
        JLB_produto = new javax.swing.JLabel();
        JTF_produto = new javax.swing.JTextField();
        JLB_valor = new javax.swing.JLabel();
        JTF_valor = new javax.swing.JTextField();
        JLB_qtdeProduto = new javax.swing.JLabel();
        JTF_qtdeProduto = new javax.swing.JTextField();
        JBT_adicionar = new javax.swing.JButton();
        JBT_vender = new javax.swing.JButton();
        JBT_estoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLB_codigo.setText("Codigo:");

        JLB_produto.setText("Produto:");

        JTF_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_produtoActionPerformed(evt);
            }
        });

        JLB_valor.setText("Valor:");

        JLB_qtdeProduto.setText("Quantidade:");

        JBT_adicionar.setText("Adicionar");
        JBT_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_adicionarActionPerformed(evt);
            }
        });

        JBT_vender.setText("Vender");
        JBT_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_venderActionPerformed(evt);
            }
        });

        JBT_estoque.setText("Estoque");
        JBT_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_estoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLB_qtdeProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_qtdeProduto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLB_valor)
                        .addGap(36, 36, 36)
                        .addComponent(JTF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JBT_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLB_produto)
                            .addComponent(JLB_codigo))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTF_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(JTF_produto))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBT_vender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBT_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLB_codigo)
                    .addComponent(JTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLB_produto)
                            .addComponent(JTF_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLB_valor)
                            .addComponent(JTF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLB_qtdeProduto)
                            .addComponent(JTF_qtdeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(JBT_vender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBT_estoque)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBT_adicionar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_produtoActionPerformed

    private void JBT_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_adicionarActionPerformed
        if (JTF_codigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não é possivel adicionar um produto sem codigo!");
        } else if (JTF_produto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não é possivel adicionar um produto sem tipo de produto!");
        } else if (JTF_valor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não é possivel adicionar um produto sem valor!");
        } else if (JTF_qtdeProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não é possivel adicionar um produto sem quantidade!");
        } else {
            String codigo, produto;
            float valor;
            int qtdeProduto;
            codigo = JTF_codigo.getText();
            produto = JTF_produto.getText();
            valor = Float.parseFloat(JTF_valor.getText());
            qtdeProduto = Integer.parseInt(JTF_qtdeProduto.getText());
            Estoque estoque = new Estoque();
            estoque.setCodigo(codigo);
            estoque.setProduto(produto);
            estoque.setValor(valor);
            estoque.setQtdeProduto(qtdeProduto);
            try {
                EstoqueDAO.adicionar(estoque);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            limparTela();
        }
    }//GEN-LAST:event_JBT_adicionarActionPerformed

    private void JBT_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_venderActionPerformed
        TelaVender telaV = new TelaVender();
        telaV.setTitle("Controle Estoque - Vender");
        telaV.setVisible(true);
        telaV.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_JBT_venderActionPerformed

    private void JBT_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_estoqueActionPerformed
        TelaEstoque telaE = new TelaEstoque();
        telaE.setTitle("Controle Estoque - Estoque");
        telaE.setVisible(true);
        telaE.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_JBT_estoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBT_adicionar;
    private javax.swing.JButton JBT_estoque;
    private javax.swing.JButton JBT_vender;
    private javax.swing.JLabel JLB_codigo;
    private javax.swing.JLabel JLB_produto;
    private javax.swing.JLabel JLB_qtdeProduto;
    private javax.swing.JLabel JLB_valor;
    private javax.swing.JTextField JTF_codigo;
    private javax.swing.JTextField JTF_produto;
    private javax.swing.JTextField JTF_qtdeProduto;
    private javax.swing.JTextField JTF_valor;
    // End of variables declaration//GEN-END:variables
}
